import { Greeting } from "./types";

export const GREETINGS: Greeting[] = [
  {
    id: 1,
    text: "爆竹声中一岁除",
    subText: "《元日》王安石",
    artist: "苏唱",
    color: "#FF6B6B",
    glowColor: "rgba(255, 107, 107, 0.6)",
    fontStyle: "brush",
    animation: "fadeUp",
  },
  {
    id: 2,
    text: "春风送暖入屠苏",
    subText: "《元日》王安石",
    artist: "向拽",
    color: "#4ECDC4",
    glowColor: "rgba(78, 205, 196, 0.6)",
    fontStyle: "cao",
    animation: "slideLeft",
  },
  {
    id: 3,
    text: "千门万户曈曈日",
    subText: "《元日》王安石",
    artist: "陆诗邀",
    color: "#FFE66D",
    glowColor: "rgba(255, 230, 109, 0.6)",
    fontStyle: "xing",
    animation: "scaleIn",
  },
  {
    id: 4,
    text: "总把新桃换旧符",
    subText: "《元日》王安石",
    artist: "秦浓浓",
    color: "#FF8C42",
    glowColor: "rgba(255, 140, 66, 0.6)",
    fontStyle: "kai",
    animation: "rotate",
  },
  {
    id: 5,
    text: "海日生残夜",
    subText: "《次北固山下》王湾",
    artist: "郑一言",
    color: "#95E1D3",
    glowColor: "rgba(149, 225, 211, 0.6)",
    fontStyle: "cao",
    animation: "fadeDown",
  },
  {
    id: 6,
    text: "江春入旧年",
    subText: "《次北固山下》王湾",
    artist: "宋余航",
    color: "#F38181",
    glowColor: "rgba(243, 129, 129, 0.6)",
    fontStyle: "xing",
    animation: "blur",
  },
  {
    id: 7,
    text: "金马玉堂春富贵",
    subText: "新春对联",
    artist: "萧莞青",
    color: "#FFD700",
    glowColor: "rgba(255, 215, 0, 0.6)",
    fontStyle: "brush",
    animation: "bounce",
  },
  {
    id: 8,
    text: "龙腾虎跃庆新年",
    subText: "新春祝福",
    artist: "陶安之",
    color: "#E84545",
    glowColor: "rgba(232, 69, 69, 0.6)",
    fontStyle: "kai",
    animation: "slideRight",
  },
  {
    id: 9,
    text: "愿得长如此",
    subText: "《守岁》苏轼",
    artist: "薛桐",
    color: "#A8E6CF",
    glowColor: "rgba(168, 230, 207, 0.6)",
    fontStyle: "cao",
    animation: "fadeUp",
  },
  {
    id: 10,
    text: "年年物候新",
    subText: "《守岁》苏轼",
    artist: "全体",
    color: "#DDA0DD",
    glowColor: "rgba(221, 160, 221, 0.6)",
    fontStyle: "xing",
    animation: "scaleIn",
  },
  {
    id: 11,
    text: "万象更新迎春到",
    subText: "新春祝福",
    artist: "彭纳之",
    color: "#87CEEB",
    glowColor: "rgba(135, 206, 235, 0.6)",
    fontStyle: "brush",
    animation: "slideLeft",
  },
  {
    id: 12,
    text: "岁岁年年人长久",
    subText: "改自《木兰花》晏殊",
    artist: "纪和程",
    color: "#FFB6C1",
    glowColor: "rgba(255, 182, 193, 0.6)",
    fontStyle: "kai",
    animation: "rotate",
  },
  {
    id: 13,
    text: "但愿人长久",
    subText: "《水调歌头》苏轼",
    artist: "于舟",
    color: "#98D8C8",
    glowColor: "rgba(152, 216, 200, 0.6)",
    fontStyle: "cao",
    animation: "blur",
  },
  {
    id: 14,
    text: "千里共婵娟",
    subText: "《水调歌头》苏轼",
    artist: "林深",
    color: "#C9B1FF",
    glowColor: "rgba(201, 177, 255, 0.6)",
    fontStyle: "xing",
    animation: "fadeDown",
  },
  {
    id: 15,
    text: "瑞雪兆丰年",
    subText: "民间谚语",
    artist: "江晚",
    color: "#FFFFFF",
    glowColor: "rgba(255, 255, 255, 0.6)",
    fontStyle: "brush",
    animation: "bounce",
  },
  {
    id: 16,
    text: "春来江水绿如蓝",
    subText: "《忆江南》白居易",
    artist: "沈言",
    color: "#7FDBDA",
    glowColor: "rgba(127, 219, 218, 0.6)",
    fontStyle: "kai",
    animation: "slideRight",
  },
];

export const COLORS = [
  "#FF1461",
  "#18FF92",
  "#5A87FF",
  "#FBF38C",
  "#FFFFFF",
  "#FFA500",
  "#DDA0DD",
  "#FF6B6B",
  "#4ECDC4",
  "#FFE66D",
];
